### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by HIT-Ygq** [kimdaebeom/Quatro-LeGO-LOAM#2]
fatal error: pmc/pmc.h: No such file or directory
 #include "pmc/pmc.h"
Quatro-LeGO-LOAM/Quatro-LeGO-LOAM/LeGO-LOAM/CMakeFiles/mapOptmization.dir/build.make:110: recipe for target 'Quatro-LeGO-LOAM/Quatro-LeGO-LOAM/LeGO-LOAM/CMakeFiles/mapOptmization.dir/src/graph.cc.o' failed

Quatro-lego-loam does not have #include "pmc/pmc.h"

**Comment by kimdaebeom** [comment]
Sorry for the late response. Did you build Quatro first?

**Comment by HIT-Ygq** [comment]
yes.but in Quatro-LeGO-LOAM doesn't have #include "pmc/pmc.h"

**Comment by kimdaebeom** [comment]
@HIT-Ygq  If you have built a package with the following [link](https://github.com/url-kaist/quatro) in the same workspace, there will be no errors. It must be same workspace.
